FROM maven:3.9-eclipse-temurin-21

RUN apt-get update && apt-get install -y git curl vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY . .

ENV SPRING_PROFILES_ACTIVE=dev
EXPOSE 8080 5005
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]