FROM node:20-bullseye

RUN apt-get update && apt-get install -y \
    python3 make g++ git curl vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

ENV NODE_ENV=development
EXPOSE 3000 9229
CMD ["npm", "run", "dev"]